### ISSUE TITLE
Don't load DebugHandler by default

### ISSUE THREAD

**Issue by ostrolucky** [symfony/monolog-bundle#165]
I consider big problem in Symfony ecosystem OOM errors for console commands. I dealt with it many times and lot of developers don't know the reason for this is DebugHandler, so they blame components which use monolog (e.g. doctrine). 

CLI commands are usually written for bulk tasks and since this bundle enables this handler by default, every action is saved to memory, even though the only Symfony Component which uses DebugHandler's content is Profiler, which we can't even use in CLI.

Of course, this can be prevented if we use prod environment or disable logging completely, but what if we still want logs written or outputted to terminal, but not saved in memory?

I think for saner defaults, this handler should be either:
- not autoloaded by default and let HttpKernel (or other Symfony component) to load it specifically, 
- not autoloaded by default in CLI
- autoloaded by default in HTTP only

Relevant: #37

**Comment by Seldaek** [comment]
The defaults are handled in the https://github.com/symfony/symfony-standard repository actually. And IMO they are ok, as you shouldn't run prod jobs in dev environment. Not sure what else to say really.

**Comment by gadelat** [comment]
No. Here are the defaults I'm talking about https://github.com/symfony/monolog-bundle/blob/master/MonologBundle.php#L35 What defaults are you talking about? If I run prod job in prod environment but I want to monitor SQL queries which doctrine is executing, I have to override those options to get rid of DebugHandler, otherwise I will end up with OOM. These are not good defaults considering DebugHandler is used normally only by symfony profiler.

**Comment by xabbuh** [comment]
@gadelat But the `DebugHandlerPass` won't do anything if the `kernel.debug` container parameter is `false` (see https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Compiler/DebugHandlerPass.php#L41-L43) which is the case when running the application in the prod environment.

**Comment by gadelat** [comment]
1. I'm saying this now for 3rd time. Sometimes you want to see debugging info even on production/with production data, or the task you are writing just naturally produces lot of logs and you want to see them. In that case, you can't set `kernel.debug` to false. Every bundle uses this for defaults. Almost nothing would get logged in that case, unless you override this in config for every component which uses monolog. So, if I want to debug my large batch task, I would need to either override this in config for every component I need logs from, or write my task with this in mind so it manipulates monolog handlers by itself. Both of them are workarounds. Personally I would rather use the third, dirty approach and just temporarily comment out the DebugHandler from MonologBundle - much less work.
2. DebugHandler is specifically for profiler only ([proof](https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Compiler/DebugHandlerPass.php#L37)), so why does it have to collect logs even in environment where symfony profiler doesn't work (CLI task)?
3. Look. Enabled debugging is not what is causing OOM errors. DebugHandler is. Most channels don't save logs to memory.
4. app/console defaults to enabling `kernel.debug`. Developer/sysadmin needs to take extra steps to prevent this. That basically means to not forget to prefix/suffix every command with env or --no-debug. And since they develop and test code without setting these extra flags/parameters, most often they WILL assume it will work on production without them, or they don't even get to learn about their existence, since they so rarely use them.
5. since I discovered that in my experience 90% cases of OOM causes DebugHandler, I don't really care so much now, because I know how to prevent that now, but most people don't know this and you are causing pain to them, because once they get this issue, it's not easy for most devs to figure out why is their script running out of memory. They get blamed by their colleagues and superiors for writing shitty code, even though all it takes is to append some stupid parameter.
6. PHP ecosystem suffers thanks to this. While trying to locate the issue, developers find piece of their code which causes OOM and they think component which they use in that piece of code is to blame, so they make shitty workarounds, such as dropping doctrine in that piece of code and using SQL directly and going around blaming the component they used. So they produce more shitty code while blaming solid symfony bundles.

**Comment by Seldaek** [comment]
@gadelat thanks for the link, I didn't realize that's what you meant by debug handler. I pushed a fix so it doesn't get registered as indeed as far as I can tell this doesn't really achieve much.

**Comment by stof** [comment]
@Seldaek this causes a big issue: running cache:clear or cache:warmup command will generate the cache, which will be reused for the other SAPI.

**Comment by Seldaek** [comment]
Hmm yeah right :/ Great. I guess we have to revert then? Any clue how to improve this situation?

**Comment by stof** [comment]
Well, we already enable it only when the profiler service is enabled. the issue in @gadelat is that turning on kernel.debug also enables the profiler by default.

**Comment by gadelat** [comment]
@stof Not sure if I understand your issue. I applied this fix, removed `app/cache/*`, run `app/console cache:warmup`, refreshed the page and profiler loaded as usual

**Comment by stof** [comment]
@gadelat if you are in dev mode, the cache is likely to be rebuilt anyway. But if it is not, your profiler won't have logs

**Comment by stof** [comment]
btw, note that if you are using a stable version of the bundle, you don't have the commit we are talking about. It is only available in the master branch currently

**Comment by gadelat** [comment]
What's the actual condition for rebuilding cache on request? Isn't it when kernel.debug is true? Which means profiler doesn't work in that condition anyway thanks to this https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Compiler/DebugHandlerPass.php#L37

**Comment by gadelat** [comment]
Yup as I thought https://github.com/symfony/config/blob/master/ConfigCache.php#L52 So container is fetched from cache only when kernel.debug is true and when it's true, DebugHandler isn't enabled anyway.

**Comment by Seldaek** [comment]
So what's the conclusion here? Should https://github.com/symfony/monolog-bundle/commit/fbbcefd7821edfaa31a48712bba0960979243c1c stay in or not? Could someone dig into this and figure out conclusively if it's a problem or not? I don't want it to end up in a release if it's an issue, but I don't have time to look at this in depth right now.

**Comment by gadelat** [comment]
@stof?

**Comment by gadelat** [comment]
So, I was playing around with DebugHandlerPass and any change I did, everything continued to work as normal (including profiler). So, I removed it completely and ... stil no change. For what purpose do you guys even have it in this bundle? Symfony profiler seems to not be using it.

**Comment by Seldaek** [comment]
I am not sure why it is there then if it's useless. Maybe things have changed in the profiler since. Anyway reopening this so it doesn't get lost.

**Comment by appeltaert** [comment]
So this is all about the profiler, why not check if it's actually enabled in the DebugHandlerPass right after checking if there's a definition for it?

https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Compiler/DebugHandlerPass.php#L40

`$container->getExtensionConfig('framework')['profiler']`

**Comment by zerkms** [comment]
And the "fix" for this issue committed as https://github.com/symfony/monolog-bundle/commit/fbbcefd7821edfaa31a48712bba0960979243c1c is a breaking change :-(

**Comment by gadelat** [comment]
@zerkms please explain

**Comment by zerkms** [comment]
@gadelat now in tests the debug log handler is not available anymore.

**Comment by gadelat** [comment]
So just add there check for test environment? Idea was that debughandler is useless in CLI, but now it seems it's useless completely.

**Comment by zerkms** [comment]
Well, I don't know how exactly to resolve it: in some functional tests I rely on its presense, and now I'm stuck with `monolog-bundle < 2.11.1` since in later versions it broke the contract.
