### ISSUE TITLE
After updating to version 3.0.1 no logs in profiler

### ISSUE THREAD

**Issue by Bukashk0zzz** [symfony/monolog-bundle#190]
After updating this package from 2.11.1 to 3.0.1 logs stops showing in web profiler. 

I use Symfony 3.1.6

![screen](https://monosnap.com/file/YRYOCk0KwJJeMcggbKfQQHKdKvdLT3.png)

**Comment by pinkeen** [comment]
The temporary fix is to remove the cache directories and let the cache warmup proceed during request.

The problem is that the debug handler is not added when cache is cleared in CLI.

The offending code (in version 2.11.2) is:
https://github.com/symfony/monolog-bundle/blob/v2.11.2/DependencyInjection/Compiler/DebugHandlerPass.php#L46

**Comment by hvt** [comment]
This was also biting me. Using `symfony/monolog-bundle:3.0.1` on `symfony/symfony:2.8` (which is not default to be honest).
