### ISSUE TITLE
Feature: command to force log file rotation

### ISSUE THREAD

**Issue by alterphp** [symfony/monolog-bundle#298]
It's not an issue but a feature suggestion.

I use `rotating_file` handler and by facing a disk space usage issue, I was needing a way to force the rotation on this log files. WDYT ?

**Comment by lyrixx** [comment]
The RotatingFileHandler is something useful for very basic website, but as soon as the website growth you will have to use a better stack (ELK, datadog, sentry, etc etc).

More ever I always prefered to use the [logrotate](https://linux.die.net/man/8/logrotate) from linux. It avoid extra PHP processing.

So I'm :-1: for this feature. And because there are no feadback from the community, I'm going to close this issue. Sorry.

But thanks for proposing such idea.
