### ISSUE TITLE
(Slack) Handler Timeout throws exception

### ISSUE THREAD

**Issue by wuestkamp** [symfony/monolog-bundle#327]
We log a lot using the Slack handler. But if slack.com is not reachable many parts of the application stop working. I tried setting the:

```
timeout: 1
connection_timeout: 1
```

but this still results in an error. Is there a way to just ignore the log if remote url is not reachable after the set timeout?

**Comment by gmponos** [comment]
AFAIK monolog does not allow you to configure those kind of stuff. You should for safety wrap your slack handler with the `WhatFailureGroup` handler.

I have created my own custom handlers for slack: https://github.com/gmponos/monolog-slack (I hope I am not crossing some kind of line here by mention this)

Since we are on the subject I would be very much interested bringing these inside symfony/monolog-bundle or bridge using a symfony client. 

I believe more monolog handlers should be using a configurable HttpClient. If there is interest I could start an RFC about it.

**Comment by gmponos** [comment]
OK.. it seems I am out of date here I just saw this: https://github.com/symfony/monolog-bundle/pull/331
and this https://github.com/symfony/monolog-bridge/blob/master/Handler/NotifierHandler.php

So things have taken their path towards this direction

**Comment by wuestkamp** [comment]
> You should for safety wrap your slack handler with the WhatFailureGroup handler.
But a WhatFailureGroup handler only catches if the timeout is exceeded from the Slack Handler, this can take a while as default timeout is set to 60.

**Comment by Tobion** [comment]
You can reduce the timeouts as you figured out yourself and wrap the handler in WhatFailureGroup

**Comment by LaurentCB** [comment]
It strikes me to see how tightly coupled this module is with sf, said one log handler ns is not reachable and the all API get unresponsive what a non-sense 🙄
